apiVersion: v1
kind: Service
metadata:
  name: flask-services
  labels:
    service: flask
spec:
  type: LoadBalancer
  selector:
    app: flask-pod
  ports:
  - name: "bind-frontend"
    protocol: "TCP"
    port: 5100
    targetPort: 5100
  - name: "bind-backend"
    protocol: "TCP"
    port: 5200
    targetPort: 5200    